// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    Youtube: typeof import('./src/components/Youtube.vue')['default']
    YoutubePlayer: typeof import('./src/components/YoutubePlayer.vue')['default']
    YoutubeVideo: typeof import('./src/components/YoutubeVideo.vue')['default']
    YoutubeVideos: typeof import('./src/components/YoutubeVideos.vue')['default']
  }
}

export { }
